In [56]:
import os 
import pandas as pd 
import psycopg

import datetime as datetime 
import datetime as dt

In [9]:
os.environ['KAGGLE_CONFIG_DIR'] = os.path.join(os.getcwd(), '.kaggle')

In [11]:
!kaggle datasets download -d karthikbhandary2/city-bike-dataset

Dataset URL: https://www.kaggle.com/datasets/karthikbhandary2/city-bike-dataset
License(s): CC0-1.0
Downloading city-bike-dataset.zip to /workspaces/ETLpipeline_design_from_kaggle_api_snowflake_andorchestrated_with_mageai
 76%|█████████████████████████████         | 3.00M/3.93M [00:00<00:00, 4.93MB/s]
100%|██████████████████████████████████████| 3.93M/3.93M [00:00<00:00, 5.16MB/s]

In [12]:
import zipfile
import pandas as pd
import os

def unzip_folder_file():
    zip_file_path = 'city-bike-dataset.zip'
    extract_dir = 'city-bike-dataset'
    
    os.makedirs(extract_dir, exist_ok=True)
    
    with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
        zip_ref.extractall(extract_dir)
    
    extracted_files = os.listdir(extract_dir)
    print("Extracted files:", extracted_files)
    
    for file_name in extracted_files:
        if file_name.endswith('.csv'):
            csv_file_path = os.path.join(extract_dir, file_name)
            break
    else:
        raise FileNotFoundError("No CSV file found in the extracted folder.")
    
    df = pd.read_csv(csv_file_path)
    return df

data_frame = unzip_folder_file()

print(data_frame.head())

Extracted files: ['bike_data.csv']
   Unnamed: 0  tripduration                 starttime  \
0           1           222  2020-09-01 00:15:58.6470
1           2           193  2020-09-01 00:49:00.7370
2           3           273  2020-09-01 00:51:44.5870
3           4          1419  2020-09-01 00:52:48.3160
4           5           254  2020-09-01 00:56:16.7170

                   stoptime  start.station.id start.station.name  \
0  2020-09-01 00:19:40.8750              3186      Grove St PATH
1  2020-09-01 00:52:14.3640              3640     Journal Square
2  2020-09-01 00:56:17.7160              3191           Union St
3  2020-09-01 01:16:28.0490              3203      Hamilton Park
4  2020-09-01 01:00:31.0870              3194    McGinley Square

   start.station.latitude  start.station.longitude  end.station.id  \
0               40.719586               -74.043117            3276
1               40.733670               -74.062500            3206
2               40.718211               -74.083639            3694
3               40.727596               -74.044247            3270
4               40.725340               -74.067622            3679

   end.station.name  end.station.latitude  end.station.longitude  bikeid  \
0  Marin Light Rail             40.714584             -74.042817   45656
1           Hilltop             40.731169             -74.057574   45352
2    Jackson Square             40.711130             -74.078900   44424
3   Jersey & 6th St             40.725289             -74.045572   42240
4        Bergen Ave             40.722104             -74.071455   42434

     usertype  birth.year gender  age  log_trip      year
0  Subscriber        1992      M   28  5.402677  Sep 2020
1  Subscriber        1991      M   29  5.262690  Sep 2020
2  Subscriber        1969      M   51  5.609472  Sep 2020
3  Subscriber        1986      M   34  7.257708  Sep 2020
4  Subscriber        1992      M   28  5.537334  Sep 2020

In [13]:
data_frame.head(10)

,Unnamed: 0,tripduration,starttime,stoptime,start.station.id,start.station.name,start.station.latitude,start.station.longitude,end.station.id,end.station.name,end.station.latitude,end.station.longitude,bikeid,usertype,birth.year,gender,age,log_trip,year
0,1,222,2020-09-01 00:15:58.6470,2020-09-01 00:19:40.8750,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,-74.042817,45656,Subscriber,1992,M,28,5.402677,Sep 2020
1,2,193,2020-09-01 00:49:00.7370,2020-09-01 00:52:14.3640,3640,Journal Square,40.733670,-74.062500,3206,Hilltop,40.731169,-74.057574,45352,Subscriber,1991,M,29,5.262690,Sep 2020
2,3,273,2020-09-01 00:51:44.5870,2020-09-01 00:56:17.7160,3191,Union St,40.718211,-74.083639,3694,Jackson Square,40.711130,-74.078900,44424,Subscriber,1969,M,51,5.609472,Sep 2020
3,4,1419,2020-09-01 00:52:48.3160,2020-09-01 01:16:28.0490,3203,Hamilton Park,40.727596,-74.044247,3270,Jersey & 6th St,40.725289,-74.045572,42240,Subscriber,1986,M,34,7.257708,Sep 2020
4,5,254,2020-09-01 00:56:16.7170,2020-09-01 01:00:31.0870,3194,McGinley Square,40.725340,-74.067622,3679,Bergen Ave,40.722104,-74.071455,42434,Subscriber,1992,M,28,5.537334,Sep 2020
5,6,1621,2020-09-01 04:04:11.0380,2020-09-01 04:31:12.9000,3225,Baldwin at Montgomery,40.723659,-74.064194,3199,Newport Pkwy,40.728745,-74.032108,45347,Subscriber,1980,M,40,7.390799,Sep 2020
6,7,293,2020-09-01 04:32:53.4590,2020-09-01 04:37:47.4300,3212,Christ Hospital,40.734786,-74.050444,3640,Journal Square,40.733670,-74.062500,39591,Subscriber,1963,F,57,5.680173,Sep 2020
7,8,1981,2020-09-01 04:33:01.0880,2020-09-01 05:06:02.6910,3199,Newport Pkwy,40.728745,-74.032108,3212,Christ Hospital,40.734786,-74.050444,45347,Subscriber,1980,M,40,7.591357,Sep 2020
8,9,3465,2020-09-01 05:06:23.3100,2020-09-01 06:04:08.5150,3203,Hamilton Park,40.727596,-74.044247,3199,Newport Pkwy,40.728745,-74.032108,42479,Subscriber,1966,M,54,8.150468,Sep 2020
9,10,641,2020-09-01 05:06:32.9270,2020-09-01 05:17:14.6910,3212,Christ Hospital,40.734786,-74.050444,3225,Baldwin at Montgomery,40.723659,-74.064194,45347,Subscriber,1980,M,40,6.463029,Sep 2020

In [23]:

data_frame['gender'] = data_frame['gender'].fillna(data_frame['gender'].mode()[0])
data_frame.isnull().sum()

Unnamed: 0                 0
tripduration               0
starttime                  0
stoptime                   0
start.station.id           0
start.station.name         0
start.station.latitude     0
start.station.longitude    0
end.station.id             0
end.station.name           0
end.station.latitude       0
end.station.longitude      0
bikeid                     0
usertype                   0
birth.year                 0
gender                     0
age                        0
log_trip                   0
year                       0
dtype: int64

In [43]:
def rename_column(data_frame):
    data_frame.rename(columns={
        'start.station.id': 'start_station_id',
        'start.station.name': 'start_station_name',
        'start.station.latitude': 'start_station_latitude',
        'start.station.longitude': 'start_station_longitude',
        'end.station.id': 'end_station_id',
        'end.station.name': 'end_station_name',
        'end.station.latitude': 'end_station_latitude',
        'end.station.longitude': 'end_station_longitude',
        'tripduration': 'trip_duration',
        'stoptime': 'stop_time',
        'starttime':'start_time'
    }, inplace=True)
    data_frame.drop(columns=['Unnamed'], errors='ignore')

    
rename_column(data_frame)

In [50]:
data_frame.pop('Unnamed: 0')

0              1
1              2
2              3
3              4
4              5
           ...
103044    103045
103045    103046
103046    103047
103047    103048
103048    103049
Name: Unnamed: 0, Length: 103049, dtype: int64

In [57]:
def transformation_data(data_frame):
    data_frame['start_time'] = pd.to_datetime(data_frame['start_time'])
    data_frame['stop_time'] = pd.to_datetime(data_frame['stop_time']) 
    data_frame['start_date'] = data_frame['start_time'].dt.date
    data_frame['stop_date'] = data_frame['stop_time'].dt.date
    
    return data_frame

In [65]:
data_frame

,trip_duration,start_time,stop_time,start_station_id,start_station_name,start_station_latitude,start_station_longitude,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth.year,gender,age,log_trip,year
0,222,2020-09-01 00:15:58.6470,2020-09-01 00:19:40.8750,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,-74.042817,45656,Subscriber,1992,M,28,5.402677,Sep 2020
1,193,2020-09-01 00:49:00.7370,2020-09-01 00:52:14.3640,3640,Journal Square,40.733670,-74.062500,3206,Hilltop,40.731169,-74.057574,45352,Subscriber,1991,M,29,5.262690,Sep 2020
2,273,2020-09-01 00:51:44.5870,2020-09-01 00:56:17.7160,3191,Union St,40.718211,-74.083639,3694,Jackson Square,40.711130,-74.078900,44424,Subscriber,1969,M,51,5.609472,Sep 2020
3,1419,2020-09-01 00:52:48.3160,2020-09-01 01:16:28.0490,3203,Hamilton Park,40.727596,-74.044247,3270,Jersey & 6th St,40.725289,-74.045572,42240,Subscriber,1986,M,34,7.257708,Sep 2020
4,254,2020-09-01 00:56:16.7170,2020-09-01 01:00:31.0870,3194,McGinley Square,40.725340,-74.067622,3679,Bergen Ave,40.722104,-74.071455,42434,Subscriber,1992,M,28,5.537334,Sep 2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103044,621,2019-09-30 23:11:40.0630,2019-09-30 23:22:01.8370,3194,McGinley Square,40.725340,-74.067622,3191,Union St,40.718211,-74.083639,26245,Subscriber,1962,M,57,6.431331,Sep 2019
103045,167,2019-09-30 23:19:02.9380,2019-09-30 23:21:50.8290,3211,Newark Ave,40.721525,-74.046305,3209,Brunswick St,40.724176,-74.050656,29525,Subscriber,1984,M,35,5.117994,Sep 2019
103046,94,2019-09-30 23:26:24.7470,2019-09-30 23:27:59.2310,3213,Van Vorst Park,40.718489,-74.047727,3483,Montgomery St,40.719420,-74.050990,26317,Subscriber,1958,M,61,4.543295,Sep 2019
103047,366,2019-09-30 23:49:00.4260,2019-09-30 23:55:06.9620,3638,Washington St,40.724294,-74.035483,3270,Jersey & 6th St,40.725289,-74.045572,29488,Subscriber,1976,M,43,5.902633,Sep 2019
103048,150,2019-09-30 23:56:30.1980,2019-09-30 23:59:00.6750,3276,Marin Light Rail,40.714584,-74.042817,3213,Van Vorst Park,40.718489,-74.047727,29498,Subscriber,1982,M,37,5.010635,Sep 2019

In [ ]:
from sqlalchemy import create_engine

def connect_postgres_database():
    # Connection string
    conn_string = 'postgresql://root:root@192.168.1.9:5432/postgres_database'  
    # Create the engine
    engine = create_engine(conn_string)
    return engine

# Example usage of the connection
if __name__ == "__main__":
    engine = connect_postgres_database()
engine.connect()